# Builds docs/RESULTADOS_NIVEL1.md from the Nivel 1 surefire XML reports.
# Usage (from the repo root, after `mvn test`):
#   powershell -ExecutionPolicy Bypass -File tools/generate-report.ps1

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$reportsDir = Join-Path $root 'SpaceInvaders_Nivel1/target/surefire-reports'
$csvPath = Join-Path $root 'casos_de_prueba_nivel1.csv'
$outPath = Join-Path $root 'docs/RESULTADOS_NIVEL1.md'

# Cases whose expected value relies on an interpretation (INSTRUCCIONES section 8 and the (*) mark).
$assumptions = @{}
foreach ($id in 'AL-12','AL-13','AL-15','AL-16','AL-19','BM-08','BM-09','BM-11','BM-13','AA-08') { $assumptions[$id] = 'S1' }
foreach ($id in 'PL-01','BC-02','GI-04') { $assumptions[$id] = 'S2' }
foreach ($id in 'PA-09','PA-10','PA-11','PA-12','PA-13') { $assumptions[$id] = 'S3' }
foreach ($id in 'UA-05','UA-07','UA-08','UA-10','UA-11') { $assumptions[$id] = 'S6' }
$assumptions['UA-13'] = '(*)'

$cases = Import-Csv -Path $csvPath -Encoding UTF8

# Collect one result per case ID from the XML reports.
$results = @{}
$counts = @{}
$smoke = @()
foreach ($file in Get-ChildItem -Path $reportsDir -Filter 'TEST-*.xml') {
    [xml]$xml = Get-Content -Path $file.FullName -Encoding UTF8 -Raw
    foreach ($tc in $xml.testsuite.testcase) {
        $problem = $tc.SelectSingleNode('failure|error')
        $skipped = $tc.SelectSingleNode('skipped')
        $status = if ($problem) { 'FAIL' } elseif ($skipped) { 'SKIPPED' } else { 'PASS' }
        if ($tc.name -notmatch '\b([A-Z]{2}-\d{2})\b') {
            $smoke += [pscustomobject]@{ Name = $tc.name; Status = $status }
            continue
        }
        $id = $Matches[1]
        $counts[$id] = 1 + [int]$counts[$id]
        $message = ''
        if ($problem) {
            $message = ($problem.GetAttribute('message') -replace '\s*\r?\n\s*', '; ' -replace '\|', '\|').Trim('; ')
        }
        $results[$id] = [pscustomobject]@{ Status = $status; Class = $tc.classname; Message = $message }
    }
}

# Every CSV ID must appear exactly once.
$problems = @()
foreach ($c in $cases) {
    if ([int]$counts[$c.id] -ne 1) { $problems += "$($c.id) appears $([int]$counts[$c.id]) times" }
}
foreach ($id in $counts.Keys) {
    if (-not ($cases.id -contains $id)) { $problems += "$id is not in the CSV" }
}

$passed = @($cases | Where-Object { $results[$_.id].Status -eq 'PASS' }).Count
$failed = @($cases | Where-Object { $results[$_.id].Status -eq 'FAIL' }).Count
$skippedCount = @($cases | Where-Object { $results[$_.id].Status -eq 'SKIPPED' }).Count
$missing = @($cases | Where-Object { -not $results[$_.id] }).Count

$sb = New-Object System.Text.StringBuilder
function Line([string]$text = '') { [void]$sb.AppendLine($text) }

Line '# Resultados Nivel 1 (black-box)'
Line
Line "Generated by ``tools/generate-report.ps1`` from ``SpaceInvaders_Nivel1/target/surefire-reports`` on $(Get-Date -Format 'yyyy-MM-dd HH:mm')."
Line
Line '## Totals'
Line
Line '| Cases | Passed | Failed | Skipped | Missing |'
Line '|---|---|---|---|---|'
Line "| $($cases.Count) | $passed | $failed | $skippedCount | $missing |"
Line
$smokeStatus = ($smoke | ForEach-Object { "$($_.Status)" }) -join ', '
Line "Smoke tests (not in the CSV): $($smoke.Count) run, status: $smokeStatus."
Line
if ($problems.Count -gt 0) {
    Line '**ID check failed:**'
    foreach ($p in $problems) { Line "- $p" }
} else {
    Line 'ID check: every CSV ID appears exactly once in the results.'
}
Line
Line '## Result per case'
Line
Line '| ID | Method | Result |'
Line '|---|---|---|'
foreach ($c in $cases) {
    $r = $results[$c.id]
    $status = if ($r) { $r.Status } else { 'MISSING' }
    Line "| $($c.id) | ``$($c.metodo)`` | $status |"
}
Line
Line '## Failures'
Line
Line 'These IDs go to the debugging phase. "Actual vs expected" is the JUnit assertion message. Expected values were taken unchanged from the CSV.'
Line
Line '| ID | Method | Expected (CSV) | Actual vs expected (JUnit) | Assumption |'
Line '|---|---|---|---|---|'
foreach ($c in $cases) {
    $r = $results[$c.id]
    if (-not $r -or $r.Status -ne 'FAIL') { continue }
    $tag = if ($assumptions.ContainsKey($c.id)) { "ASSUMPTION-DEPENDENT ($($assumptions[$c.id]))" } else { '-' }
    $expected = $c.resultado_esperado -replace '\|', '\|'
    Line "| $($c.id) | ``$($c.metodo)`` | $expected | $($r.Message) | $tag |"
}
Line
Line '## Deviations from the instructions'
Line
Line '- **JDK:** JDK 21 was not installed, so the tests were compiled and run on Temurin JDK 23 with `maven.compiler.release` 21. The project owners decided this.'
Line '- **`Alien.Bomb`:** it is a non-static inner class (constructor `Bomb(Alien, int, int)` per `javap`), so BM-* tests create bombs with `owner.new Bomb(x, y)`.'
Line '- **Sprite placement:** in Board-level cases, sprites are built and then placed with `setX`/`setY`, so those cases do not depend on the constructor defects found in AL/SX.'
Line '- No expected value from the CSV was changed.'

[System.IO.Directory]::CreateDirectory((Split-Path -Parent $outPath)) | Out-Null
[System.IO.File]::WriteAllText($outPath, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote $outPath  (passed $passed, failed $failed, skipped $skippedCount, missing $missing)"
if ($problems.Count -gt 0) { Write-Host ($problems -join "`n"); exit 1 }
